### PR TITLE
Fix Issue #102

### LINKED ISSUE #102: Connector and Service level suggestions are not working
**Description:**
Suggestions in the service scope and connector scope are not get completed

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Purpose
Resolves #102 

ezgif com-video-to-gif 4

ezgif com-video-to-gif 5

### CODE REVIEW

File: modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/TreeVisitor.java [hunk 1]
```diff
@@ -330,44 +331,73 @@ public void visit(BLangConnector connectorNode) {
...
-            connectorNode.varDefs.forEach(varDef -> this.acceptNode(varDef, connectorEnv));
-            connectorNode.actions.forEach(action -> this.acceptNode(action, connectorEnv));
+            if (connectorNode.actions.isEmpty() && connectorNode.varDefs.isEmpty()) {
+                this.isCursorWithinBlock(connectorNode.getPosition(), connectorEnv);
+            } else {
+                // Since the connector def does not contains a block statement, we consider the block owner only.
+                // Here it is Connector Definition
+                this.blockOwnerStack.push(connectorNode);
+                connectorNode.varDefs.forEach(varDef -> {
+                    // Cursor position is calculated against the resource parameter scope resolver
```
Comment (NipunaMarcus) [inline modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/TreeVisitor.java]: is this comment correct? isn't it using ConnectorScopeResolver?

Comment (nadeeshaan) [reply modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/TreeVisitor.java]: Fixed
